Controllers/DepartmentController.cs
using SampleAjaxDemo.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleAjaxDemo.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(DepartmentVM model)
        {
            model.SaveOrupdateDepartment(model.DepartmentMasterDto);
            return Json(model, JsonRequestBehavior.AllowGet);

        }
    }
}

Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleAjaxDemo.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/OrganizationController.cs
using SampleAjaxDemo.Models;
using SampleAjaxDemo.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleAjaxDemo.Controllers
{
    public class OrganizationController : Controller
    {
        // GET: Organization
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Save(OrganizationVM model) {
            model.SaveOrUpdateOrganization(model.organizationMasterDto);
            return Json(model, JsonRequestBehavior.AllowGet);

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/json2.js"></script>
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(function () {
            //$(".nav-link").on("click", function () {
            //    $('.active').removeClass("active");
            //    $(this).addClass("active");
            //});
        })
    </script>
    <style>
        .activeTab {
            background-color: darkred;
            color: white;
        }

        .nav-link {
            border-radius: 10px 0 10px 0;
            border: 2px solid;
            margin: 0 5px 0 5px;
            color: white;
        }

        .card-header {
            background-color: #c82333;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-danger navbar-dark">
            <a class="navbar-brand" href="#">MVC Lightweight Demo &nbsp;&nbsp;&nbsp;</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Home")">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Organization")">Add Organization</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Department")">Add Department</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Employee")">Add Emloyees</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="row">
            <br />
            @RenderBody()
        </div>
    </div>
</body>
</html>